/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.event;

/**
 *
 * @author 7320
 */
public class CheckBoxTambahan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckBoxTambahan.class.getName());

    /**
     * Creates new form CheckBoxTambahan
     */
    public CheckBoxTambahan() {
        initComponents();
    }
    
    private String formatRupiah(int nominal) {
        return "Rp. " + String.format(java.util.Locale.forLanguageTag("id-ID"), "%,d", nominal);
    }
    
    private void hitungTotal() {
        int total = 25000;
        
        if(cbGulaAren.isSelected()) {
            total += 3000;
        }
        
        if(cbSusuOat.isSelected()) {
            total += 5000;
        }
        
        if(cbExtraShot.isSelected()) {
            total += 4000;
        }
        
        lblTotal.setText(formatRupiah(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGulaAren = new javax.swing.JCheckBox();
        cbSusuOat = new javax.swing.JCheckBox();
        cbExtraShot = new javax.swing.JCheckBox();
        lblTotalJudul = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambahan Kopi");

        jLabel1.setText("Tambahan :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Latte - Rp 25.000");

        cbGulaAren.setText("Gula Aren (+ 3.000)");
        cbGulaAren.addItemListener(this::cbGulaArenItemStateChanged);

        cbSusuOat.setText("Susu Oat (+ 5.000)");
        cbSusuOat.addActionListener(this::cbSusuOatActionPerformed);

        cbExtraShot.setText("Extra Shot (+ 4.000)");
        cbExtraShot.addActionListener(this::cbExtraShotActionPerformed);

        lblTotalJudul.setText("Total : ");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTotal.setText("Rp 25.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbGulaAren)
                    .addComponent(cbSusuOat)
                    .addComponent(cbExtraShot)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalJudul)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGulaAren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSusuOat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbExtraShot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalJudul)
                    .addComponent(lblTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSusuOatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSusuOatActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbSusuOatActionPerformed

    private void cbExtraShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExtraShotActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbExtraShotActionPerformed

    private void cbGulaArenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGulaArenItemStateChanged
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbGulaArenItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckBoxTambahan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbExtraShot;
    private javax.swing.JCheckBox cbGulaAren;
    private javax.swing.JCheckBox cbSusuOat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalJudul;
    // End of variables declaration//GEN-END:variables
}
