/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author 7320
 */
public class BorderLayoutMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName());

    /**
     * Creates new form BorderLayoutMenu
     */
    public BorderLayoutMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lbllNamaKopi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        lblHarga = new javax.swing.JLabel();
        lblJamBuka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Kopi");
        setPreferredSize(new java.awt.Dimension(560, 360));
        getContentPane().setLayout(new java.awt.BorderLayout(6, 6));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Kopi Pilihan Hari ini");
        getContentPane().add(lblJudul, java.awt.BorderLayout.PAGE_START);

        lbllNamaKopi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbllNamaKopi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllNamaKopi.setText("Americano");
        lbllNamaKopi.setPreferredSize(new java.awt.Dimension(110, 20));
        getContentPane().add(lbllNamaKopi, java.awt.BorderLayout.LINE_START);

        txtDeskripsi.setEditable(false);
        txtDeskripsi.setColumns(20);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setRows(5);
        txtDeskripsi.setText("Kopi Hitam no sugar");
        txtDeskripsi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDeskripsi);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga.setText("20.000");
        lblHarga.setPreferredSize(new java.awt.Dimension(110, 20));
        getContentPane().add(lblHarga, java.awt.BorderLayout.LINE_END);

        lblJamBuka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJamBuka.setText("Buka Setiap Hari, 08:00 - 17:00");
        getContentPane().add(lblJamBuka, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BorderLayoutMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJamBuka;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lbllNamaKopi;
    private javax.swing.JTextArea txtDeskripsi;
    // End of variables declaration//GEN-END:variables
}
