/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author 7320
 */
public class CardLayoutPesan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName());

    /**
     * Creates new form CardLayoutPesan
     */
    public CardLayoutPesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPilih = new javax.swing.JPanel();
        lblLangkah1 = new javax.swing.JLabel();
        lblNamaKopi = new javax.swing.JLabel();
        txtKopi = new javax.swing.JTextField();
        btnLanjut = new javax.swing.JButton();
        panelKonfirmasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPesanan = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblLangkah1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLangkah1.setText("Langkah 1 dari 2 - Pilih Kopi");

        lblNamaKopi.setText("Nama Kopi :");

        txtKopi.setText("Latte");

        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(this::btnLanjutActionPerformed);

        javax.swing.GroupLayout panelPilihLayout = new javax.swing.GroupLayout(panelPilih);
        panelPilih.setLayout(panelPilihLayout);
        panelPilihLayout.setHorizontalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLangkah1)
                    .addGroup(panelPilihLayout.createSequentialGroup()
                        .addComponent(lblNamaKopi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilihLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );
        panelPilihLayout.setVerticalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLangkah1)
                .addGap(18, 18, 18)
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaKopi)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );

        getContentPane().add(panelPilih, "pilih");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Langkah 2 dari 2 - Pilih Kopi");

        lblPesanan.setText("Kopi yang Dipilih : ");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout panelKonfirmasiLayout = new javax.swing.GroupLayout(panelKonfirmasi);
        panelKonfirmasi.setLayout(panelKonfirmasiLayout);
        panelKonfirmasiLayout.setHorizontalGroup(
            panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblPesanan))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addComponent(btnSelesai)
                .addContainerGap())
        );
        panelKonfirmasiLayout.setVerticalGroup(
            panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(panelKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        getContentPane().add(panelKonfirmasi, "konfirmasi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        lblPesanan.setText("Kopi yang Dipilih: " + txtKopi.getText());
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "konfirmasi");
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "pilih");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan Diterima");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CardLayoutPesan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLangkah1;
    private javax.swing.JLabel lblNamaKopi;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JPanel panelKonfirmasi;
    private javax.swing.JPanel panelPilih;
    private javax.swing.JTextField txtKopi;
    // End of variables declaration//GEN-END:variables
}
