/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.container;

/**
 *
 * @author 7320
 */
public class FramePesanDialog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePesanDialog.class.getName());

    /**
     * Creates new form FramePesanDialog
     */
    public FramePesanDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogKonfirmasi = new javax.swing.JDialog();
        lblPesanDiterima = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        lblAmericano = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();

        dialogKonfirmasi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogKonfirmasi.setTitle("Konfirmasi");
        dialogKonfirmasi.setModal(true);

        lblPesanDiterima.setText("Pesanan Anda Sudah Diterima. Terima Kasih.");

        btnOK.setText("OK");
        btnOK.addActionListener(this::btnOKActionPerformed);

        javax.swing.GroupLayout dialogKonfirmasiLayout = new javax.swing.GroupLayout(dialogKonfirmasi.getContentPane());
        dialogKonfirmasi.getContentPane().setLayout(dialogKonfirmasiLayout);
        dialogKonfirmasiLayout.setHorizontalGroup(
            dialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogKonfirmasiLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblPesanDiterima)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(138, 138, 138))
        );
        dialogKonfirmasiLayout.setVerticalGroup(
            dialogKonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogKonfirmasiLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblPesanDiterima)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addGap(55, 55, 55))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kedai Kopi - Pesan");

        lblAmericano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAmericano.setText("Americano - Rp20.000");

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(this::btnPesanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmericano)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesan)
                        .addGap(42, 42, 42)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblAmericano)
                .addGap(18, 18, 18)
                .addComponent(btnPesan)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        dialogKonfirmasi.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        dialogKonfirmasi.pack();
        dialogKonfirmasi.setLocationRelativeTo(this);
        dialogKonfirmasi.setVisible(true);
    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePesanDialog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesan;
    private javax.swing.JDialog dialogKonfirmasi;
    private javax.swing.JLabel lblAmericano;
    private javax.swing.JLabel lblPesanDiterima;
    // End of variables declaration//GEN-END:variables
}
