/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.event;

/**
 *
 * @author 7320
 */
public class ComboBoxHarga extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ComboBoxHarga.class.getName());

    /**
     * Creates new form ComboBoxHarga
     */
    public ComboBoxHarga() {
        initComponents();
    }
    
    private String formatRupiah(int nominal) {
        return "Rp. " + String.format(java.util.Locale.forLanguageTag("id-ID"), "%,d", nominal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPilihKopi = new javax.swing.JLabel();
        cmdKopi = new javax.swing.JComboBox<>();
        lblHargaJudul = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPilihKopi.setText("Pilih Kopi");

        cmdKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Americano", "Latte", "Espresso", "Cappuccino" }));
        cmdKopi.addActionListener(this::cmdKopiActionPerformed);

        lblHargaJudul.setText("Harga :");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHarga.setText("Rp. 15.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPilihKopi)
                        .addGap(18, 18, 18)
                        .addComponent(cmdKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHargaJudul)
                        .addGap(18, 18, 18)
                        .addComponent(lblHarga)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPilihKopi)
                    .addComponent(cmdKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaJudul)
                    .addComponent(lblHarga))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKopiActionPerformed
        // TODO add your handling code here:
        String kopi = (String) cmdKopi.getSelectedItem();
        int harga = switch(kopi) {
            case "Espresso" -> 18000;
            case "Americano" -> 20000;
            default -> 25000;
        };
        
        lblHarga.setText(formatRupiah(harga));
    }//GEN-LAST:event_cmdKopiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ComboBoxHarga().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmdKopi;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHargaJudul;
    private javax.swing.JLabel txtPilihKopi;
    // End of variables declaration//GEN-END:variables
}
